version: '3'
  db:
    image: postgres:10.6
    volumes:
     - postgresql:/var/lib/postgresql/data
    env_file:
    - docker.env
    ports:
    - "5432:5432"
  django:
    build: .
    user: "1000"
    volumes:
    - ./stemmata:/code/stemmata
    ports:
    - "8000:8000"
    env_file:
    - docker.env
    depends_on:
    - db
    working_dir: /code/
    command: /code/venv/bin/python3.6 ./manage.py runserver 0.0.0.0:8000